vczb/sagu-ui

src/packages/Slider/mock.ts
src/packages/Slider/test.tsx

Added the first batch of tests for the `Slider` component.

Added test file for Slider component

---

src/packages/Paper/index.tsx
src/packages/Paper/styles.ts
src/packages/Paper/test.tsx

This PR adds a left placement option for the Paper component. May need additional guidance on expectations.
Closes #6

Paper - Adds Left Placement

---

src/packages/NumberField/test.tsx

Let's increase the code coverage :D

Added NumberField tests

---

src/packages/Paper/test.tsx

Adds test for `active` property.
Closes #14

Paper - Adds Tests

---

src/packages/CheckBox/test.tsx
src/packages/Radio/test.tsx

Adds tests for the Radio and Checkbox components.
Closes #22

Checkbox, Radio - Adds Tests

---

src/packages/Modal/index.tsx
src/packages/Modal/stories.tsx
src/packages/Modal/styles.ts
src/packages/Modal/test.tsx

Modal component, including 3 sub-components (Modal-header, Modal-body and Modal-footer)

Modal component #8

---

EXAMPLES.md

@vczb Please review it, and tell is this correct this time.

Created a Timer using Reactjs and sagu-ui

---

EXAMPLES.md

Added a new Product Cards Listing example in EXAMPLES.md
It contributes to #31

added an example in EXAMPLES.md

---

EXAMPLES.md

This is a todo application made with sagu-ui.

added todo app example

---

CONTRIBUTING.md

As discussed in #50 I have added CONTRIBUTING.md File, have a look at it.

Added CONTRIBUTING.mdd file

---

src/packages/Skeleton/index.tsx
src/packages/Skeleton/stories.tsx
src/packages/Skeleton/styles.ts

I would like to contribute a skeleton component. Please take a look.
And feel free to give comments.
Thanks!

Add an skeleton component

---

src/packages/Slider/Dot.tsx
src/packages/Slider/index.tsx
src/packages/Slider/styles.ts

I would like to contribute this, to solve the issue #3 
Please take a look.
Thanks! @vczb

Add dots to slider

---

.github/workflows/ci.yml
.github/workflows/storybook.yml

Issue #61 
- Upgrade actions/checkout to v3
- Upgrade actions/setup-node to v3

Upgraded github actions

---

src/packages/Label/index.tsx
src/packages/TextField/index.tsx
src/packages/TextField/styles.ts

fixed: remove padding-top for TextField if no label is provided.

remove padding-top for TextField

---

src/packages/Box/index.tsx
src/packages/Box/stories.tsx
src/packages/Box/styles.ts

Create Box component

---

.github/workflows/ci.yml

use the right version on the CI

Fix CI node version

---

src/packages/Breadcrumb/test.tsx
src/packages/Paper/test.tsx

Skip failing tests

---

CONTRIBUTING.md

- Inverted steps 6 and 7 (#88 step 1)
- Updated step 8 to "Test your changes." (#88 step 2)
- Fixed code of conduct URL (#88 step 3)
resolved #88

Update CONTRIBUTING.md (resolve #88)

---

README.md

feat: added contributors info

---

README.md

- Added related emojis to each and every section in readme.
- will change the emoji if it doesn't suits the section name, can ping me back
Ready for the review and feedback

Added emojis for each section in README

---

src/packages/Pagination/stories.tsx
src/packages/index.ts

- Added a Pagination component story to Storybook for better visualization and testing.
- Maintained state in the Storybook story to demonstrate the Pagination component's functionality.
Ready for review and feedback.

Added Pagination Component to Storybook

---

src/packages/Alert/test.tsx
src/packages/index.ts

Component tested - Alert
Screenshot - Alert test passed

test: add test for alert component

---

src/packages/Badge/index.tsx
src/packages/Badge/stories.tsx
src/packages/Badge/styles.tsx
src/styles/theme/index.ts

Implemented Badge component:
- Introduced `size` prop to adjust the badge size (xsmall, small, medium, large).
- Introduced `shape` prop to specify the shape of the badge (circle, square, rectangle).
- Allowed for custom colors through the `color` prop.
- Improved Storybook controls to showcase both string and number types for the `content` prop.

New Badge Component

---

src/packages/AutoComplete/index.tsx
src/packages/AutoComplete/mock.ts
src/packages/AutoComplete/stories.tsx
src/packages/AutoComplete/styles.ts
src/packages/AutoComplete/test.tsx
src/packages/Tag/index.tsx
src/packages/Tag/styles.ts

- Created Auto Complete component which supports comboBox and freeSolo modes and implemented different scenarios for both the modes taking material UI as reference
- Added test cases for all the scenarios

feat: Add auto complete component with comboBox and freeSolo modes

---

src/packages/Switch/test.tsx

Hi, I have add the tests for switch component and create the PR for #7 
Here is the screenshot for the test:

test: add test for switch component

---

src/packages/ToolTip/test.tsx

Component tested - Tooltip
Screenshot - Tooltip test passed

test: add test for tooltip

---

src/packages/Box/__snapshots__/test.tsx.snap
src/packages/Box/test.tsx

Component tested - Box
Screenshot - Box tests passed

test : Adds test for Box

---

src/packages/Badge/__snapshots__/test.tsx.snap
src/packages/Badge/test.tsx

Component tested - Badge
Screenshot - Badge tests passed

test : Adds test for Badge

---

src/packages/GridMain/__snapshots__/test.tsx.snap
src/packages/GridMain/test.tsx

Component tested - GridMain
Screenshots - GridMain tests passed

test : Adds test for GridMain component

---

src/packages/Divider/__snapshots__/test.tsx.snap
src/packages/Divider/test.tsx
src/packages/GridFluid/__snapshots__/test.tsx.snap
src/packages/GridFluid/test.tsx

Component tested - Divider and GridFluid
Screenshots - Divider and GridFluid  tests passed

test : Adds test for Divider and GridFluid component

---

src/packages/Highlight/test.tsx
src/packages/Ribbon/__snapshots__/test.tsx.snap
src/packages/Ribbon/test.tsx

Component tested - Highlight and Ribbon
Screenshots - Highlight and Ribbon tests passed

test : Adds test for Highlight and Ribbon component

---

src/packages/Toaster/index.tsx
src/packages/Toaster/stories.tsx
src/packages/Toaster/styles.ts

Responsiveness: Utilizing the vw units, the toaster's position scales based on the viewport width, ensuring it is always optimally placed for a variety of screen sizes.
Configurable Duration: Allows users to set the duration for which the toaster notification is visible.
Closable Option: Provides the option to either allow or prevent users from manually closing the notification.
Styling & Themes: Integrated with the existing theme and leveraged the severity-based color coding from the Alert component to ensure consistency in design and user experience.
Positioning: Positioned fixed at the bottom right by default, ensuring minimal obstruction to the user's workflow.
Severity Levels: Supports different severity levels such as 'error', 'warning', 'info', and 'success' to provide contextually …

Implement Responsive Toaster Notification Feature

---

src/packages/TextContent/__snapshots__/test.tsx.snap
src/packages/TextContent/test.tsx

test: add test for TextContent component

---

src/styles/global.ts
src/styles/theme/index.ts

add root css var to fix shadow theme changing
spread color variable into theme object

Fix colors
